### PR TITLE
Remove key column (visibility) filter in github_my_repository. Closes #93

### LINKED ISSUE #93: Remove key column (visibility) filter in github_my_repository
**Describe the bug**
Due to a change in the query plan in FDW, the filter visibility will be dropped off for an interim fix for the failing GitHub sherlock controls. Refer [here](https://github.com/turbot/steampipe-postgres-fdw/issues/117)

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by bigdatasourav**
# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  name,
  owner_login,
  full_name
from
  github_my_repository
order by
  full_name;
+------------------------------------------+---------------+-------------------------------------------------+
| name                                     | owner_login   | full_name                                       |
+------------------------------------------+---------------+-------------------------------------------------+
| steampipe-plugin-pokemon                 | bigdatasourav | bigdatasourav/steampipe-plugin-pokemon          |
| test                                     | bigdatasourav | bigdatasourav/test                              |
| turbot-test                              | bigdatasourav | bigdatasourav/turbot-test                       |
| go-kit                                   | turbot        | turbot/go-kit                                   |
| hibp-go                                  | turbot        | turbot/hibp-go                                  |
| steampipe                                | turbot        | turbot/steampipe                                |
| steampipe-hub-actions                    | turbot        | turbot/steampipe-hub-actions                    |
| steampipe-mod-alicloud-compliance        | turbot        | turbot/steampipe-mod-alicloud-compliance        |
| steampipe-mod-alicloud-thrifty           | turbot        | turbot/steampipe-mod-alicloud-thrifty           |
| steampipe-mod-aws-compliance             | turbot        | turbot/steampipe-mod-aws-compliance             |
| steampipe-mod-aws-tags                   | turbot        | turbot/steampipe-mod-aws-tags                   |
| steampipe-mod-aws-thrifty                | turbot        | turbot/steampipe-mod-aws-thrifty                |
| steampipe-mod-aws-top10                  | turbot        | turbot/steampipe-mod-aws-top10                  |
| steampipe-mod-azure-compliance           | turbot        | turbot/steampipe-mod-azure-compliance           |
| steampipe-mod-azure-tags                 | turbot        | turbot/steampipe-mod-azure-tags                 |
| steampipe-mod-azure-thrifty              | turbot        | turbot/steampipe-mod-azure-thrifty              |
| steampipe-mod-bitbucket-sherlock         | turbot        | turbot/steampipe-mod-bitbucket-sherlock         |
| steampipe-mod-digitalocean-thrifty       | turbot        | turbot/steampipe-mod-digitalocean-thrifty       |
| steampipe-mod-gcp-compliance             | turbot        | turbot/steampipe-mod-gcp-compliance             |
| steampipe-mod-gcp-labels                 | turbot        | turbot/steampipe-mod-gcp-labels                 |
| steampipe-mod-gcp-thrifty                | turbot        | turbot/steampipe-mod-gcp-thrifty                |
| steampipe-mod-github-sherlock            | turbot        | turbot/steampipe-mod-github-sherlock            |
| steampipe-mod-googleworkspace-compliance | turbot        | turbot/steampipe-mod-googleworkspace-compliance |
| steampipe-mod-ibm-compliance             | turbot        | turbot/steampipe-mod-ibm-compliance             |

> select
  name,
  private,
  visibility,
  owner_login
from
  github_my_repository
where
  not private;
+------------------------------------------+---------+------------+---------------+
| name                                     | private | visibility | owner_login   |
+------------------------------------------+---------+------------+---------------+
| steampipe-mod-azure-compliance           | false   | public     | turbot        |
| steampipe-mod-jira-sherlock              | false   | public     | turbot        |
| steampipe-plugin-sdk                     | false   | public     | turbot        |
| steampipe-plugin-fastly                  | false   | public     | turbot        |
| steampipe-plugin-terraform               | false   | public     | turbot        |
| steampipe-plugin-prometheus              | false   | public     | turbot        |
| steampipe-mod-oci-tags                   | false   | public     | turbot        |
| steampipe-plugin-net                     | false   | public     | turbot        |
| steampipe-plugin-docker                  | false   | public     | turbot        |
| steampipe-plugin-slack                   | false   | public     | turbot        |
| steampipe-mod-digitalocean-thrifty       | false   | public     | turbot        |
| steampipe-plugin-equinix                 | false   | public     | turbot        |
| steampipe-plugin-rss                     | false   | public     | turbot        |
| steampipe-plugin-cloudflare              | false   | public     | turbot        |
| steampipe-plugin-gcp                     | false   | public     | turbot        |
| steampipe-plugin-hibp                    | false   | public     | turbot        |
| steampipe-mod-aws-tags                   | false   | public     | turbot        |
| steampipe-plugin-ipstack                 | false   | public     | turbot        |
| steampipe-mod-gcp-thrifty                | false   | public     | turbot        |
| steampipe-plugin-zendesk                 | false   | public     | turbot        |
| steampipe-plugin-turbot                  | false   | public     | turbot        |
| turbot-test                              | false   | public     | bigdatasourav |
```
</details>

### CODE REVIEW

File: github/table_github_branch_protection.go [hunk 1]
```diff
@@ -69,16 +69,19 @@ func tableGitHubRepositoryBranchProtectionGet(ctx context.Context, d *plugin.Que
 	}
 
 	get := func(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
-		ptotection, _, err := client.Repositories.GetBranchProtection(ctx, owner, repo, branchName)
+		protection, _, err := client.Repositories.GetBranchProtection(ctx, owner, repo, branchName)
 		if err != nil {
-			if strings.Contains(err.Error(), "404") {
+			// For private and archived repositories, user who do not have owner/admin access will get the below error
```
Comment (misraved) [inline github/table_github_branch_protection.go:74]:
```suggestion
			// For private and archived repositories, users who do not have owner/admin access will get the below error
```

File: github/table_github_branch_protection.go [hunk 2]
```diff
@@ -69,16 +69,19 @@ func tableGitHubRepositoryBranchProtectionGet(ctx context.Context, d *plugin.Que
...
+			// 403 Upgrade to GitHub Pro or make this repository public to enable this feature.
+			// For repositories owners the api will return nil if it is private and archived
```
Comment (misraved) [inline github/table_github_branch_protection.go:76]:
```suggestion
			// For repository owners the API will return nil if the repository is private and archived
```

**Review by misraved — COMMENTED** [review]
Make minor updates to the comments

**Review by misraved — APPROVED** [review]
